---
dev_cache_dir: /tmp/cacheansible
local_home: "{{ lookup('env','HOME') }}"

# Go
golang_version: "1.20.3"
golang_tarball_repo: "https://go.dev/dl"
golang_tarball: "go{{ golang_version }}.linux-amd64.tar.gz"
golang_download_location: "{{ golang_tarball_repo }}/{{ golang_tarball }}"

golang_gopath: "{{ local_home }}/go"
golang_install_dir: "/usr/local"
golang_env:
  GOPATH: "{{ golang_gopath }}"
  GOROOT: "{{ golang_install_dir }}/go"

golang_version_string: "go version go{{ golang_version }} linux/amd64"

# Neovim
nvim_tarball: "nvim-linux64.tar.gz"
nvim_download_location: "https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz"
nvim_config_repo: "git@github.com:za-arthur/nvim.git"

# Hugo
hugo_latest_url: "https://api.github.com/repos/gohugoio/hugo/releases/latest"
hugo_tarball_url: "https://github.com/gohugoio/hugo/releases/download"
hugo_tarball: "hugo_{{ latest_version }}_Linux-64bit.tar.gz"
hugo_download_location: "{{ hugo_tarball_url }}/{{ latest_version_tag }}/{{ hugo_tarball }}"

# Lazygit
lazygit_latest_url: "https://api.github.com/repos/jesseduffield/lazygit/releases/latest"
lazygit_tarball_url: "https://github.com/jesseduffield/lazygit/releases/download"
lazygit_tarball: "lazygit_{{ latest_version }}_Linux_x86_64.tar.gz"
lazygit_download_location: "{{ lazygit_tarball_url }}/{{ latest_version_tag }}/{{ lazygit_tarball }}"

# Act
act_latest_url: "https://api.github.com/repos/nektos/act/releases/latest"
act_tarball_url: "https://github.com/nektos/act/releases/download"
act_tarball: "act_Linux_x86_64.tar.gz"
act_download_location: "{{ act_tarball_url }}/{{ latest_version_tag }}/{{ act_tarball }}"
