theme = "dark_plus"

[editor]
mouse = false
rulers = [80]

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"
