---
- name: "Ensure cache dir exists"
  file:
    path: "{{ common_cache_dir }}"
    state: directory

- name: "Download latest JetBrainsMono release"
  get_url:
    url: "{{ nerd_font_url }}"
    dest: "{{ common_cache_dir }}"

- name: "Ensure fonts dir exists"
  file:
    path: "{{ local_home }}/.local/share/fonts"
    state: directory

- name: "Extract JetBrainsMono tarball"
  unarchive:
    src: "{{ common_cache_dir }}/{{ nerd_font_tarball }}"
    dest: "{{ local_home }}/.local/share/fonts"

- name: "Rebuild fonts cache"
  become: yes
  ansible.builtin.command: "fc-cache -v -f"

- name: "Set JetBrainsMono font"
  ansible.builtin.command: "gsettings set org.gnome.desktop.interface monospace-font-name \"JetBrainsMono NF 13\""

