---
- name: "Install tilix"
  become: true
  ansible.builtin.apt:
    name: "tilix"
    state: latest

- name: "Select tilix as default terminal"
  become: true
  community.general.alternatives:
    link: "/usr/bin/x-terminal-emulator"
    name: "x-terminal-emulator"
    path: "/usr/bin/tilix"
    state: selected

