---
- name: "Ansible Playbook to setup a new laptop"
  hosts: "laptop"
  roles:
    - role: "common"
      tags:
        - "common"
    - role: "dev"
      tags:
        - "dev"
    - role: "cli"
      tags:
        - "cli"
