---
- name: "Ansible Playbook to setup a new macOS laptop"
  hosts: "macos_laptop"
  roles:
    - role: "macos.cli"
      tags:
        - "cli"
    - role: "dev"
      tags:
        - "dev"
    - role: "macos.dev"
      tags:
        - "dev"
