---
- name: "Ansible Playbook to setup a new Ubuntu laptop"
  hosts: "laptop"
  roles:
    - role: "common"
      tags:
        - "common"
    - role: "ubuntu.dev"
      tags:
        - "dev"
    - role: "ubuntu.cli"
      tags:
        - "cli"
