---
- name: "Ansible Playbook to setup a new Ubuntu laptop"
  hosts: "macos_laptop"
  roles:
    - role: "common"
      tags:
        - "common"
    - role: "dev"
      tags:
        - "dev"
    - role: "ubuntu.dev"
      tags:
        - "dev"
    - role: "cli"
      tags:
        - "cli"
