---
- name: "Ensure cache dir exists"
  file:
    path: "{{ common_cache_dir }}"
    state: directory

- name: "Check if cargo is installed"
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: "Download rustup"
  get_url:
    url: "https://sh.rustup.rs"
    dest: "{{ common_cache_dir }}/sh.rustup.rs"
    mode: "0755"
  when: cargo_exists is failed

- name: "Install rust/cargo"
  shell: "{{ common_cache_dir }}/sh.rustup.rs -y"
  when: cargo_exists is failed
