---
- name: "Update Homebrew"
  community.general.homebrew:
    update_homebrew: true

- name: "Install go"
  community.general.homebrew:
    name: "go"
    state: latest

- name: "Import nvim"
  import_tasks: "nvim.yml"

- name: "Install xclip"
  become: true
  ansible.builtin.apt:
    name: "xclip"
    state: latest

- name: "Install lazygit"
  community.general.homebrew:
    name: "lazygit"
    state: latest

- name: "Install delta"
  community.general.homebrew:
    name: "git-delta"
    state: latest

- name: "Import pgenv"
  import_tasks: "pgenv.yml"
  tags:
    - "pgenv"

- name: "Import PostgreSQL dev tools"
  import_tasks: "pgtools.yml"

- name: "Import llvm"
  import_tasks: "llvm.yml"

- name: "Checkout pyenv"
  community.general.homebrew:
    name: "pyenv"
    state: latest
