---
- name: "Import go"
  import_tasks: "go.yml"
  tags:
    - "go"

- name: "Import nvim"
  import_tasks: "nvim.yml"
  tags:
    - "nvim"

- name: "Install xclip"
  become: true
  ansible.builtin.apt:
    name: "xclip"
    state: latest

- name: "Import pgenv"
  import_tasks: "pgenv.yml"
  tags:
    - "pgenv"

- name: "Import tools"
  import_tasks: "tools.yml"
  tags:
    - "dev_tools"

