---
- name: "Install bear"
  become: true
  ansible.builtin.apt:
    name: "bear"
    state: latest

- name: "Install pgformatter"
  become: true
  ansible.builtin.apt:
    name: "pgformatter"
    state: latest
