---
- name: "Install gitui"
  include_role:
    name: "github_release"
  vars:
    name: "gitui"
    version_cmd: "/usr/local/bin/gitui --version"
    version_string: "gitui VERSION"
    bin_dir: "/usr/local/bin"
    latest_url: "{{ gitui_latest_url }}"
    download_url: "{{ gitui_download_location }}"
    tarball_name: "{{ gitui_tarball }}"
    tarball_strip: 1

- name: "Install act"
  include_role:
    name: "github_release"
  vars:
    name: "act"
    version_cmd: "/usr/local/bin/act --version"
    version_string: "act version VERSION"
    bin_dir: "/usr/local/bin"
    latest_url: "{{ act_latest_url }}"
    download_url: "{{ act_download_location }}"
    tarball_name: "{{ act_tarball }}"
    tarball_add_file: "act"

- name: "Install bear"
  become: true
  ansible.builtin.apt:
    name: "bear"
    state: latest

- name: "Install pgformatter"
  become: true
  ansible.builtin.apt:
    name: "pgformatter"
    state: latest
