---
- name: "Get dotfile name from {{ dotfile_path }}"
  set_fact:
    dotfile_dst: "{{ dst_directory | default(local_home) }}/\
      {{ dst_prefix | default('.') }}\
      {{ dotfile_path | basename | split('_') | last }}"

- name: "Backup existing {{ dotfile_dst }}"
  copy:
    src: "{{ dotfile_dst }}"
    dest: "{{ dotfile_dst }}.back"
  ignore_errors: true

- name: "Create symlink {{ dotfile_dst }}"
  file:
    src: "{{ dotfile_path }}"
    dest: "{{ dotfile_dst }}"
    state: link
    force: true
