---
- name: "Install Hack TrueType fonts"
  tags:
    - "nerd_font"
  ansible.builtin.apt:
    name: "fonts-hack-ttf"
    state: "latest"

- name: "Rebuild fonts cache"
  ansible.builtin.command: "fc-cache -v -f"

- name: "Set Hack 13 font"
  tags:
    - "nerd_font"
  become: false
  ansible.builtin.command: "gsettings set org.gnome.desktop.interface monospace-font-name \"Hack 13\""
