---
- name: "Install JetBrains fonts"
  tags:
    - "fonts_jetbrains"
  become: yes
  ansible.builtin.apt:
    name: "fonts-jetbrains-mono"
    state: latest

- name: "Rebuild fonts cache"
  become: yes
  ansible.builtin.command: "fc-cache -v -f"

- name: "Set JetBrains font"
  tags:
    - "fonts_jetbrains"
  ansible.builtin.command: "gsettings set org.gnome.desktop.interface monospace-font-name \"JetBrains Mono 13\""
