---
- name: "Ensure cache dir exists"
  file:
    path: "{{ common_cache_dir }}"
    state: directory

- name: "Download homebrew installation script"
  get_url:
    url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
    dest: "{{ common_cache_dir }}"

- name: "Give execution permissions to the installation script"
  file:
    path: "{{ common_cache_dir  }}/install.sh"
    mode: "a+x"

- name: "Install homebrew"
  ansible.builtin.shell: "{{ common_cache_dir }}/install.sh"
