---
- name: "Install syncthing"
  block:
    - name: "Download syncthing GPG key"
      become: true
      ansible.builtin.get_url:
        url: "https://syncthing.net/release-key.gpg"
        dest: "/usr/share/keyrings/syncthing-archive-keyring.gpg"
        force: true

    - name: "Add syncthing apt repository"
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
        filename: "syncthing"
        update_cache: true
        state: present

    - name: "Install syncthing package"
      become: true
      ansible.builtin.apt:
        name: "syncthing"
        state: latest

- name: "Install obsidian"
  block:
    - name: "Register the current obsidian version"
      ansible.builtin.package_facts:
        manager: auto

    - name: "Retrieve latest obsidian version"
      uri:
        url: "{{ obsidian_latest_url }}"
        return_content: true
      register: obsidian_latest

    - name: "Set latest obsidian version"
      set_fact:
        obsidian_version: "{{ obsidian_latest.json['name'] }}"

    - name: "Download and install obsidian package"
      block:
        - name: "Ensure cache dir exists"
          file:
            path: "{{ common_cache_dir }}"
            state: directory

        - name: "Check that the obsidian deb file exists"
          stat:
            path: "{{ common_cache_dir }}/{{ obsidian_deb }}"
          register: obsidian_deb_cache

        - name: "Download the obsidian deb file"
          get_url:
            url: "{{ obsidian_download_location }}"
            dest: "{{ common_cache_dir }}"
          when: not obsidian_deb_cache.stat.exists

        - name: "Install obsidian package"
          become: true
          ansible.builtin.apt:
            deb: "{{ common_cache_dir }}/{{ obsidian_deb }}"
      when: >-
        ('obsidian' in ansible_facts.packages and ansible_facts.packages['obsidian'][0]['version'] != obsidian_version) or
        ('obsidian' not in ansible_facts.packages)
