---
- name: "Install wezterm flatpak package"
  become: yes
  community.general.flatpak:
    name: "org.wezfurlong.wezterm"
    state: present

- name: "Create wezterm configuration file"
  include_tasks: "dotfiles_create.yml"
  vars:
    dotfile_path: "{{ role_path }}/files/dot_wezterm.lua"

- name: "Select wezterm as default terminal"
  become: yes
  community.general.alternatives:
    link: "/usr/bin/x-terminal-emulator"
    name: "x-terminal-emulator"
    path: "/var/lib/flatpak/exports/bin/org.wezfurlong.wezterm"
    state: selected
