---
- name: "Ensure Applications dir exists"
  ansible.builtin.file:
    path: "{{ local_home }}/Applications"
    state: directory

- name: "Check that iTerm2 is installed"
  ansible.builtin.stat:
    path: "{{ local_home }}/Applications/iTerm2.app"
  register: iterm2_app

- name: "Install iTerm2"
  block:
    - name: "Ensure cache dir exists"
      ansible.builtin.file:
        path: "{{ common_cache_dir }}"
        state: directory

    - name: "Download iTerm2"
      ansible.builtin.get_url:
        url: "{{ iterm2_download_location }}"
        dest: "{{ common_cache_dir }}/{{ iterm2_zip }}"

    - name: "Extract iTerm2"
      unarchive:
        src: "{{ common_cache_dir }}/{{ iterm2_zip }}"
        dest: "{{ local_home }}/Applications/iTerm2.app"
  when: not iterm2_app.stat.exists

