---
- name: "Install Wezterm"
  community.general.homebrew_cask:
    name: "wezterm"
    state: latest

- name: "Install JetBrainsMono nerd font"
  tags:
    - "nerd_font"
  community.general.homebrew_cask:
    name: "font-jetbrains-mono-nerd-font"
    state: latest
    update_homebrew: true

- name: "Install powerlevel10k"
  community.general.homebrew:
    name: "powerlevel10k"
    state: latest

- name: "Install zsh-history-substring-search"
  community.general.homebrew:
    name: "zsh-history-substring-search"
    state: latest

- name: "Install zsh-syntax-highlighting"
  community.general.homebrew:
    name: "zsh-syntax-highlighting"
    state: latest

- name: "Install lsd"
  tags:
    - "cli_tools"
  community.general.homebrew:
    name: "lsd"
    state: latest

- name: "Install yq"
  tags:
    - "cli_tools"
  community.general.homebrew:
    name: "yq"
    state: latest

- name: "Install fd"
  tags:
    - "cli_tools"
  community.general.homebrew:
    name: "fd"
    state: latest

- name: "Install fzf"
  tags:
    - "cli_tools"
  community.general.homebrew:
    name: "fzf"
    state: latest

- name: "Install rg"
  tags:
    - "cli_tools"
  community.general.homebrew:
    name: "rg"
    state: latest
