---
- name: "Install and configure ghostty"
  block:
    - name: "Install ghostty"
      community.general.homebrew_cask:
        name: "ghostty"
        state: latest

    - name: "Create a symlink to the ghostty config directory"
      file:
        src: "{{ role_path }}/files/config/ghostty"
        dest: "{{ local_home }}/.config/ghostty"
        state: link

- name: "Import fish"
  import_tasks: "fish.yml"

- name: "Install JetBrainsMono nerd font"
  community.general.homebrew_cask:
    name: "font-jetbrains-mono-nerd-font"
    state: latest
    update_homebrew: true
    install_options: force

- name: "Install lsd"
  community.general.homebrew:
    name: "lsd"
    state: latest

- name: "Install yq"
  community.general.homebrew:
    name: "yq"
    state: latest

- name: "Install fd"
  community.general.homebrew:
    name: "fd"
    state: latest

- name: "Install fzf"
  community.general.homebrew:
    name: "fzf"
    state: latest

- name: "Install rg"
  community.general.homebrew:
    name: "rg"
    state: latest

- name: "Install bat"
  community.general.homebrew:
    name: "bat"
    state: latest
