---
- name: "Install and configure ghostty"
  block:
    - name: "Install ghostty"
      community.general.homebrew_cask:
        name: "ghostty"
        state: latest

    - name: "Create a symlink to the ghostty config directory"
      file:
        src: "{{ role_path }}/files/config/ghostty"
        dest: "{{ local_home }}/.config/ghostty"
        state: link

- name: "Install JetBrainsMono nerd font"
  tags:
    - "nerd_font"
  community.general.homebrew_cask:
    name: "font-jetbrains-mono-nerd-font"
    state: latest
    update_homebrew: true
    install_options: force

- name: "Install powerlevel10k"
  community.general.homebrew:
    name: "powerlevel10k"
    state: latest

- name: "Install zsh-history-substring-search"
  community.general.homebrew:
    name: "zsh-history-substring-search"
    state: latest

- name: "Install zsh-syntax-highlighting"
  community.general.homebrew:
    name: "zsh-syntax-highlighting"
    state: latest

- name: "Install zsh-autosuggestions"
  community.general.homebrew:
    name: "zsh-autosuggestions"
    state: latest

- name: "Install lsd"
  tags:
    - "cli_tools"
  community.general.homebrew:
    name: "lsd"
    state: latest

- name: "Install yq"
  tags:
    - "cli_tools"
  community.general.homebrew:
    name: "yq"
    state: latest

- name: "Install fd"
  tags:
    - "cli_tools"
  community.general.homebrew:
    name: "fd"
    state: latest

- name: "Install fzf"
  tags:
    - "cli_tools"
  community.general.homebrew:
    name: "fzf"
    state: latest

- name: "Install rg"
  tags:
    - "cli_tools"
  community.general.homebrew:
    name: "rg"
    state: latest
