---
- name: "Import iTerm2"
  tags:
    - "iterm2"
  import_tasks: "iterm2.yml"

- name: "Import Oh My Zsh"
  tags:
    - "oh_my_zsh"
  import_tasks: "oh_my_zsh.yml"

- name: "Install JetBrainsMono nerd font"
  tags:
    - "nerd_font"
  community.general.homebrew_cask:
    name: "font-jetbrains-mono-nerd-font"
    state: latest
    update_homebrew: true
