---
- name: "Check that oh-my-zsh.sh"
  ansible.builtin.stat:
    path: "{{ local_home }}/.oh-my-zsh/oh-my-zsh.sh"
  register: ohmyzsh_sh

- name: "Install Oh My Zsh"
  block:
    - name: "Ensure cache dir exists"
      ansible.builtin.file:
        path: "{{ common_cache_dir }}"
        state: directory

    - name: "Download Oh My Zsh installation script"
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "{{ common_cache_dir }}/install_ohmyzsh.sh"

    - name: "Run Oh My Zsh installation script"
      command: "/bin/bash {{ common_cache_dir }}/install_ohmyzsh.sh"
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"
  when: not ohmyzsh_sh.stat.exists
