---
- name: "Ensure cache dir exists"
  file:
    path: "{{ dev_cache_dir }}"
    state: directory

- name: "Retrieve latest act version"
  uri:
    url: "{{ act_latest_url }}"
    return_content: true
  register: act_latest

- name: "Set latest act version"
  set_fact:
    act_version: "{{ act_latest.json['tag_name'] | regex_replace('^v','') }}"

- name: "Check that the act tar exists"
  stat:
    path: "{{ dev_cache_dir }}/{{ act_tarball }}"
  register: act_tar

- name: "Download the act tarball"
  get_url:
    url: "{{ act_download_location }}"
    dest: "{{ dev_cache_dir }}"
  when: not act_tar.stat.exists

- name: "Extract the act tarball"
  become: yes
  unarchive:
    src: "{{ dev_cache_dir }}/{{ act_tarball }}"
    remote_src: yes
    dest: "/usr/local/bin"
    extra_opts:
      - "--add-file"
      - "act"
