---
- name: "Add helix repository"
  become: yes
  ansible.builtin.apt_repository:
    repo: "ppa:maveonair/helix-editor"
    state: present

- name: "Install helix"
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    name: "helix"
    state: latest
