---
- name: "Gather package facts"
  package_facts:
    manager: apt

- name: "Install helix"
  block:
    - name: "Add helix repository"
      become: true
      ansible.builtin.apt_repository:
        repo: "ppa:maveonair/helix-editor"
        state: present

    - name: "Install helix package"
      become: true
      ansible.builtin.apt:
        update_cache: yes
        name: "helix"
        state: latest
  when: "'helix' not in ansible_facts.packages"

- name: "Create helix configuration directory"
  file:
    path: "{{ local_home }}/.config/helix"
    state: directory

- name: "Create helix configuration files"
  include_role:
    name: "common"
    tasks_from: "dotfiles_create"
  vars:
    dst_directory: "{{ local_home }}/.config/helix"
    dst_prefix: ""
  with_fileglob: "{{ role_path }}/files/helix/*"
  loop_control:
    loop_var: dotfile_path
