---
- name: "Ensure cache dir exists"
  file:
    path: "{{ dev_cache_dir }}"
    state: directory

- name: "Retrieve latest hugo version"
  uri:
    url: "{{ hugo_latest_url }}"
    return_content: true
  register: hugo_latest

- name: "Set latest hugo version"
  set_fact:
    hugo_version: "{{ hugo_latest.json['tag_name'] | regex_replace('^v','') }}"

- name: "Check that the Hugo tar exists"
  stat:
    path: "{{ dev_cache_dir }}/{{ hugo_tarball }}"
  register: hugo_tar

- name: "Download the Hugo tarball"
  get_url:
    url: "{{ hugo_download_location }}"
    dest: "{{ dev_cache_dir }}"
  when: not hugo_tar.stat.exists

- name: "Extract the Go tarball"
  become: yes
  unarchive:
    src: "{{ dev_cache_dir }}/{{ hugo_tarball }}"
    dest: "/usr/local/bin"
    remote_src: yes
