---
- name: "Register the current lazygit version"
  command: "/usr/local/bin/lazygit --version"
  register: "lazygit_bin_version"
  changed_when: false
  ignore_errors: yes

- name: "Retrieve latest lazygit version"
  uri:
    url: "{{ lazygit_latest_url }}"
    return_content: true
  register: lazygit_latest

- name: "Set latest lazygit version"
  set_fact:
    lazygit_version: "{{ lazygit_latest.json['tag_name'] | regex_replace('^v','') }}"

- name: "Download and install lazygit"
  block:
    - name: "Ensure cache dir exists"
      file:
        path: "{{ dev_cache_dir }}"
        state: directory

    - name: "Check that the lazygit tar exists"
      stat:
        path: "{{ dev_cache_dir }}/{{ lazygit_tarball }}"
      register: lazygit_tar

    - name: "Download the lazygit tarball"
      get_url:
        url: "{{ lazygit_download_location }}"
        dest: "{{ dev_cache_dir }}"
      when: not lazygit_tar.stat.exists

    - name: "Extract the lazygit tarball"
      become: yes
      unarchive:
        src: "{{ dev_cache_dir }}/{{ lazygit_tarball }}"
        remote_src: yes
        dest: "/usr/local/bin"
        extra_opts:
          - "--add-file"
          - "lazygit"
  when: "lazygit_bin_version.stdout is not match(lazygit_version_string)"
