---
- name: "Load a variable file based on the OS"
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - 'vars'

- name: "Import go"
  import_tasks: "go.yml"
  tags:
    - "go"

- name: "Import nvim"
  import_tasks: "nvim.yml"
  tags:
    - "nvim"

- name: "Import pgenv"
  import_tasks: "pgenv.yml"
  tags:
    - "pgenv"

- name: "Import tools"
  import_tasks: "tools.yml"
  tags:
    - "dev_tools"

