---
- name: "Import go"
  import_tasks: "go.yml"
  tags:
    - "go"
    - "update_tools"

- name: "Import tools"
  import_tasks: "tools.yml"
  tags:
    - "dev_tools"
    - "update_tools"

- name: "Import helix"
  import_tasks: "helix.yml"
  tags:
    - "helix"
    - "update_tools"

- name: "Import lsp"
  import_tasks: "lsp.yml"
  tags:
    - "lsp"
    - "update_tools"
