---
- name: "Import go"
  import_tasks: "go.yml"
  tags:
    - "go"

- name: "Import hugo"
  import_tasks: "hugo.yml"
  tags:
    - "hugo"

- name: "Import lazygit"
  import_tasks: "lazygit.yml"
  tags:
    - "lazygit"
