---
- name: "Install dua"
  include_role:
    name: "common"
    tasks_from: "github_release"
  vars:
    name: "dua"
    version_cmd: "/usr/local/bin/dua/dua --version"
    version_string: "dua VERSION"
    bin_dir: "/usr/local/bin/dua"
    latest_url: "{{ dua_latest_url }}"
    download_url: "{{ dua_download_location }}"
    tarball_name: "{{ dua_tarball }}"
    tarball_strip: 1
