---
- name: "Ensure cache dir exists"
  file:
    path: "{{ cli_cache_dir }}"
    state: directory

- name: "Retrieve latest wezterm version"
  uri:
    url: "{{ wezterm_latest_url }}"
    return_content: true
  register: wezterm_latest

- name: "Set latest wezterm version"
  set_fact:
    wezterm_version: "{{ wezterm_latest.json['tag_name'] }}"

- name: "Check that the wezterm tar exists"
  stat:
    path: "{{ cli_cache_dir }}/{{ wezterm_deb }}"
  register: wezterm_deb_cache

- name: "Download the wezterm deb"
  get_url:
    url: "{{ wezterm_download_location }}"
    dest: "{{ cli_cache_dir }}"
  when: not wezterm_deb_cache.stat.exists

- name: "Install wezterm package"
  become: yes
  ansible.builtin.apt:
    deb: "{{ cli_cache_dir }}/{{ wezterm_deb }}"

- name: "Set wezterm dot file path"
  set_fact:
    wezterm_dotfile: "{{ role_path }}/files/dot_wezterm.lua"

- name: "Create wezterm configuration file"
  include_role:
    name: "common"
    tasks_from: "dotfiles_create"
  vars:
    dotfile_path: "{{ wezterm_dotfile }}"

- name: "Select wezterm as default terminal"
  become: yes
  community.general.alternatives:
    link: "/usr/bin/x-terminal-emulator"
    name: "x-terminal-emulator"
    path: "/usr/bin/open-wezterm-here"
    state: selected
