---
- name: "Install lsd (ls command)"
  tags:
    - "lsd-ls"
  become: true
  ansible.builtin.apt:
    name: "lsd"
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: "Install dua"
  tags:
    - "dua"
  include_role:
    name: "github_release"
  vars:
    name: "dua"
    version_cmd: "/usr/local/bin/dua/dua --version"
    version_string: "dua VERSION"
    bin_dir: "/usr/local/bin/dua"
    latest_url: "{{ dua_latest_url }}"
    download_url: "{{ dua_download_location }}"
    tarball_name: "{{ dua_tarball }}"
    tarball_strip: 1

- name: "Install yq"
  tags:
    - "yq"
  include_role:
    name: "github_release"
  vars:
    name: "yq"
    version_cmd: "/usr/local/bin/yq --version"
    version_string: ".*version VERSION_TAG"
    bin_dir: "/usr/local/bin/"
    latest_url: "{{ yq_latest_url }}"
    download_url: "{{ yq_download_location }}"
    release_bin_name: "{{ yq_release_bin_name }}"

- name: "Install ripgrep"
  become: true
  ansible.builtin.apt:
    name: "ripgrep"
    state: latest

- name: "Install fdfind"
  become: true
  ansible.builtin.apt:
    name: "fd-find"
    state: latest

- name: "Create symlink fd"
  file:
    src: "/usr/bin/fdfind"
    dest: "{{ local_home }}/.local/bin/fd"
    state: link

